on:
  schedule:
    - cron: '0 *6 * * *'
  push:
    branches: main

name: Scrape UNC Hospitals police crime log

jobs:
  render:
    name: Scrape UNC Hospitals police crime log
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("tidyr","dplyr","lubridate","readr","jsonlit","hms","digest"))'
      - name: Scrape the data
        run: Rscript scrape_crime_log.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New entries in crime log - data updated.' || echo "No changes to commit"
          git push origin || echo "No changes to commit"